[common]
	#Whether guidebook should be dispensed
	dispenseGuidebook = true

[radiation]
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	backgroundRadiationDissipation = 1.0
	# Default: 300.0
	# Range: 0.0 ~ 1.7976931348623157E308
	iodineResistanceThreshold = 300.0
	# Default: 0.8
	# Range: 1.0 ~ 1.7976931348623157E308
	iodineRadreduction = 1.0
	radiationSystemEnabled = true
	#Whether ores like Uranium emit radiation
	oresEmitRadiation = true
	#How frequently ores random tick radiation. Value of 1 is fastest rate.
	# Default: 20
	# Range: > 1
	oreRadiationEmitRate = 20
